ame: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5 
      - run: ls -l # Liste les fichier du r√©pertoire courant
      - run: cat README.md 